# This file is located in your Spring-Cloud-Config-Server's Git repository
# e.g., Spring-Cloud-Config-Server/examination-cell-dev.yml

server:
  port: 8082

spring:
  application:
    name: ExaminationService # <--- Ensure this is present and matches the one in bootstrap.yml
  data:
    mongodb:
      uri: mongodb://localhost:27017/examdb

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: exam-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    com.example.examinationcell: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
