spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  main:
    allow-bean-definition-overriding: true

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example.userservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

# Resilience4j configuration
resilience4j:
  retry:
    instances:
      default:
        max-attempts: 2
        wait-duration: 1s

  circuitbreaker:
    instances:
      default:
        register-health-indicator: true
        sliding-window-size: 3
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
